gradient concept output: reproduce error from notebooks and solve it
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [64, 768]], which is output 0 of AsStrid.